### ISSUE TITLE
Markdown lists are unformatted

### ISSUE THREAD

**Issue by bukzor** [Doriandarko/claude-engineer#232]
The default css styling includes this rule:

```css
menu,
ol,
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
```

It's not clear to me where it comes from, but the result is that when Claude uses markdown lists they are rendered with no indication of a list.
